### ISSUE TITLE
Type detect on native async functions returns "asyncfunction" on node instead of "function"

### ISSUE THREAD

**Issue by qraynaud** [chaijs/type-detect#100]
On node 8.1.0 (probably also on older versions supporting async functions) calling returns `asyncfunction`:
```js
const typeDetect = require('type-detect');

typeDetect(async function() {})
```

I believe this is not correct and should return `function` since async functions are noting more than normal functions returning promises from the function user's PoV.

What are your thoughts on this?

**Comment by keithamus** [comment]
Hey @qraynaud thanks for the issue.

The proposal you put forward is very sensible, async functions are just functions that return Promises - and in a dynamically typed language where there is no assurance of return types, there is no need to differentiate between those. Completely agree.

But, I think our current behaviour is correct - because ultimately what `type-detect` gives you `Object#toString` in a easier to use and much faster and more cross-engine compatible way. To expand on that a little bit - you could read through https://github.com/chaijs/type-detect/pull/92 and the concluding comment here: https://github.com/chaijs/type-detect/pull/92#issuecomment-294697157 - which I would give the same reasoning for here.

So I'll close this issue under the same grounds as #92. If you'd like to, we can certainly discuss it further and we can always re-open it if there is strong evidence to show that we should set a precedent here, and override what `Object#toString` gives us.

**Comment by qraynaud** [comment]
@keithamus: I agree with your reasoning but would like to add a comment to get to the bottom of this. Another possible issue with the current `asyncfunction` is that Babel compiled code returns `function` for those (obviously) and that makes type checks using chai behave differently if you compiled code for node 6 and node 8 which is a problem for testing libraries.

For this use case I believe returning `function` might prevent a lot of problems in test suites upgraded to node 7.6+.

Any thoughts on this?

**Comment by keithamus** [comment]
Yes, unfortunately many compatibility layers - including Babel, and some polyfills unfortunately do not ship with setting `[Symbol.toStringTag]` and as such will fall back ES5 counterparts. I believe, in the case of babel, you can load in a toStringTag polyfill which would emulate the correct behaviour.

Given the above rubric we set for type-detect (namely cross compatibility) I would be happy to discuss fixing implementations (either here or on their side) to ensure that all implementations return `"AsyncFunction"` per the spec. I'm not sure how we can do that with Babel right now.

**Comment by keithamus** [comment]
So to continue; a brief look at Babel - it looks to provide no mechanism for us to be able to detect if a function is an AsyncFunction or not. Unless I am mistaken there is no way for us to fix this incompatibility, and it would have to be addressed in Babel. It looks as though https://github.com/babel/babel/issues/4691 may well suffice for us to handle this.

**Comment by qraynaud** [comment]
I believe you are right about this. It would be better if we got `asyncfunction` everywhere to be more spec compliant. Hope it gets fixed in Babel soon. Thanks a lot for your insights here.
