### ISSUE TITLE
Symbol issue (lowercase)

### ISSUE THREAD

**Issue by doasync** [chaijs/type-detect#102]
The following assertion fails:

`assert(type(Symbol()) === 'Symbol');`  // AssertionError

It is taken from the README.md file. The actual result of the type-check is 'symbol' (lowercase)

So, `type(Symbol()) !== Symbol.name`.

**Comment by keithamus** [comment]
Thanks for the issue @doasync 

The reason is because `typeof Symbol() == "symbol"` which is an early-return in type-detect:

https://github.com/chaijs/type-detect/blob/c7895e499ecc0a93c567adef9fa2b33eec13d2ab/index.js#L54-L57

We could probably change that to:

```js
  var typeofObj = typeof obj;
  if (typeofObj !== 'object') {
    return typeofObj === 'symbol' ? 'Symbol' : typeofObj;
  }
```

We'd welcome a PR, which includes that change plus a change to the tests:
https://github.com/chaijs/type-detect/blob/c7895e499ecc0a93c567adef9fa2b33eec13d2ab/test/new-ecmascript-types.js#L71-L73

**Comment by doasync** [comment]
May be it should return lowercase string... because `Symbol` is primitive data type (as well as boolean, null, undefined, number, string)
