### ISSUE TITLE
Travis build is failing

### ISSUE THREAD

**Issue by meeber** [chaijs/type-detect#131]
Looks related to https://github.com/travis-ci/travis-ci/issues/8836. There are suggestions of either adding `sudo: required` to the config, or adding the `--no-sandbox` flag to the karma launcher for Chrome.

> 15 01 2018 03:14:44.739:INFO [launcher]: Starting browser ChromeHeadless
> 15 01 2018 03:14:45.013:ERROR [launcher]: Cannot start ChromeHeadless
> 	[0115/031444.860776:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /opt/google/chrome/chrome-sandbox is owned by root and has mode 4755.
> Failed to generate minidump.

**Comment by keithamus** [comment]
This is new, and annoying. It looks like on Linux the sandbox requires root to make a chrooted jail for forked Chrome processes, so that they cannot do nefarious things. Luckily, in CI we're in a Docker container with limited access anyway, so I think `--no-sandbox` is the way to go (IIRC in Travis `sudo: false` will use a VM rather than a Docker container, so is much slower)
