### ISSUE TITLE
Requesting version bump

### ISSUE THREAD

**Issue by Alloyed** [chaijs/type-detect#146]
Hi, I'm trying to use chai 4.3.4 in an environment that is neither node.js or the browser, and it works fine except for the fact that the polyfill to detect the global object as of type-detect 4.0.5 does not work in my environment (`global` does not exist, and neither does `self`, but `globalThis` does). Recent changes in #142 would absolutely work for my case, but there's no npm package right now that would pick them up.

Could type-detect and Chai get version bumps with these recent changes? thank you

**Comment by keithamus** [comment]
Hey @Alloyed thanks for the issue!

Would you like to make a PR bumping the version? I'll merge it and release it and we can look to update Chai too!

**Comment by mstoykov** [comment]
I would really appreciate if a new version is released.

Looking around there doesn't seem to be a version number to be bumped and given #147 it seems like the way to release a version has been lost in the transition.

As an outside contributor it seems there is no action I can take in order to help the release, except for asking in issues at this time. 

If there is something that can be done, please give some pointers and I can try to add it back to the CI, but it seems in the end someone will need to tag a release. Which isn't going to be doable by an outside contributor

**Comment by 43081j** [comment]
We probably just do them through GitHub releases now

Maybe @koddsson can help? (I'm still out travelling so not of much help yet)

**Comment by koddsson** [comment]
I just cut [`chai@4.5.0`](https://github.com/chaijs/chai/releases/tag/v4.5.0). Feel free to comment or reopen if something is still wrong.
